### ISSUE TITLE
Broken Link in README.md

### ISSUE THREAD

**Issue by warlicks** [wrightrc/Bioprocess-Book#1]
The link in the README is directing to [https://github.com/wrightrc/Bioprocess-Book/blob/master/wrightrc.github.io/Bioprocess-Book](https://github.com/wrightrc/Bioprocess-Book/blob/master/wrightrc.github.io/Bioprocess-Book) rather than [https://wrightrc.github.io/Bioprocess-Book/](https://wrightrc.github.io/Bioprocess-Book/).

**Comment by wrightrc** [comment]
Ah thanks! Just in time for class!

Hope you all are doing well. Loved your holiday card!
