### ISSUE TITLE
Should this be C_A0^2?

### ISSUE THREAD

**Issue by arc3699** [wrightrc/Bioprocess-Book#4]
https://github.com/wrightrc/Bioprocess-Book/blob/7f1dd88f163eb3ab6bb6140139d10da76de7ef96/02-ideal-reactors.Rmd#L150

since C_A = C_A0(1-x_A) and the rate law is -r_A = kC_A^2 shouldn't the whole C_A term be squared, not just (1-x_A)?

**Comment by wrightrc** [comment]
No, when converting from C_A to x_A the C_A0's cancel out and you are just left with one. See lines 42 and 43 .
